[build-system]
requires = ["setuptools>=68.0"]
build-backend = "setuptools.build_meta"

[project]
name = "certgraph"
version = "0.5.0"
description = "Utility for exploring and mapping X509 certificate chains."
readme = "README.md"
requires-python = ">=3.12"
license = { file = "LICENSE" }
authors = [
    { name = "Chris Adshead" },
]
dependencies = [
    "cryptography",
    "networkx",
    "pydot",
    "rapidfuzz",
]

[project.optional-dependencies]
dev = [
    "black",
    "pytest",
    "pytest-cov",
]
docs = [
    "sphinx",
    "sphinx-autodoc-typehints",
    "sphinx-rtd-theme",
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
testpaths = ["tests"]